package com.collegefinder.backend.college;
import java.util.*;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/colleges") @CrossOrigin(origins = "*")
public class CollegeController {
  private final List<College> colleges = List.of(
    new College(1L,"Greenfield Institute of Technology","Bengaluru","Karnataka","A modern engineering college with active student clubs.","Separate furnished hostels, Wi-Fi, dining hall and 24/7 security.","86% placement rate · Highest package: ₹18 LPA",List.of(new Course("B.Tech Computer Science","4 years","₹1,20,000 / year"),new Course("B.Tech Artificial Intelligence","4 years","₹1,35,000 / year"),new Course("MBA","2 years","₹1,80,000 / year"))),
    new College(2L,"Riverside College of Arts & Science","Chennai","Tamil Nadu","Known for its practical learning and approachable faculty.","On-campus hostel for all genders with study rooms and laundry.","78% placement rate · Highest package: ₹10 LPA",List.of(new Course("B.Sc Computer Science","3 years","₹75,000 / year"),new Course("B.Com","3 years","₹55,000 / year"),new Course("BBA","3 years","₹70,000 / year"))),
    new College(3L,"Northstar Medical University","Hyderabad","Telangana","Health sciences campus with teaching hospital exposure.","Residential blocks close to campus and a student health centre.","Internship support and hospital recruitment assistance.",List.of(new Course("B.Pharm","4 years","₹1,10,000 / year"),new Course("B.Sc Nursing","4 years","₹95,000 / year"),new Course("Physiotherapy","4.5 years","₹1,25,000 / year"))),
    new College(4L,"Malla Reddy University","Hyderabad","Telangana","A private university at Maisammaguda, Dulapally, Hyderabad, offering programmes across engineering, management, agriculture and allied health sciences.","Separate modern hostel facilities for boys and girls, with internet access, digital-library access, gym and yoga facilities.","A dedicated placement cell provides training, certifications and placement support across disciplines. Contact the university for current placement statistics.",List.of(new Course("B.Tech Computer Science & Engineering","4 years","Contact admissions for current fee"),new Course("B.Tech Artificial Intelligence & Machine Learning","4 years","Contact admissions for current fee"),new Course("BBA","3 years","Contact admissions for current fee"))),
    new College(5L,"VNR Vignana Jyothi Institute of Engineering and Technology","Hyderabad","Telangana","An autonomous engineering institute known for technology-focused undergraduate programmes.","Separate hostel accommodation is available; confirm availability and fees with the institute.","Training and placement support with campus recruitment opportunities.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹1,35,000 / year (indicative)"),new Course("B.Tech Information Technology","4 years","₹1,35,000 / year (indicative)"),new Course("B.Tech Electronics & Communication","4 years","₹1,35,000 / year (indicative)"))),
    new College(6L,"Chaitanya Bharathi Institute of Technology","Hyderabad","Telangana","An established engineering college in Gandipet offering undergraduate and postgraduate technical programmes.","Hostel support is available; check the college for current room and mess options.","Dedicated training and placement activities for eligible students.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹1,50,000 / year (indicative)"),new Course("B.Tech Artificial Intelligence & Data Science","4 years","₹1,50,000 / year (indicative)"),new Course("MBA","2 years","₹90,000 / year (indicative)"))),
    new College(7L,"Gokaraju Rangaraju Institute of Engineering and Technology","Hyderabad","Telangana","A technical institute at Bachupally with engineering and management programmes.","Separate hostel facilities and student support services are available on or near campus.","Placement preparation, recruiter engagement and career guidance are provided.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹1,30,000 / year (indicative)"),new Course("B.Tech Artificial Intelligence & Machine Learning","4 years","₹1,30,000 / year (indicative)"),new Course("B.Tech Electrical & Electronics","4 years","₹1,30,000 / year (indicative)"))),
    new College(8L,"CMR Institute of Technology","Hyderabad","Telangana","An engineering and technology institute offering programmes in computing, electronics and management.","Separate hostel and transport options are available; verify current facilities with the college.","The placement cell organises training, internships and campus drives.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹1,10,000 / year (indicative)"),new Course("B.Tech Data Science","4 years","₹1,10,000 / year (indicative)"),new Course("MBA","2 years","₹80,000 / year (indicative)"))),
    new College(9L,"Malla Reddy Engineering College","Hyderabad","Telangana","An autonomous engineering college in the Malla Reddy group of institutions.","Hostel, transport, sports and gym facilities are available; contact the college for current charges.","Training and placement support is provided for engineering students.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹1,15,000 / year (indicative)"),new Course("B.Tech Cyber Security","4 years","₹1,15,000 / year (indicative)"),new Course("B.Tech Mechanical Engineering","4 years","₹1,15,000 / year (indicative)"))),
    new College(10L,"Mahindra University","Hyderabad","Telangana","A private university in Hyderabad with engineering, management and design-focused programmes.","Residential hostel accommodation and campus-life facilities are available.","Career services, internships and placement preparation support students.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹5,00,000 / year (indicative)"),new Course("B.Tech Artificial Intelligence","4 years","₹5,00,000 / year (indicative)"),new Course("MBA","2 years","₹7,00,000 / year (indicative)"))),
    new College(11L,"Anurag University","Hyderabad","Telangana","A multidisciplinary university offering engineering, pharmacy, management and science programmes.","Separate student accommodation and campus support facilities are available.","Placement training, internships and recruiter engagement are offered.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹1,25,000 / year (indicative)"),new Course("B.Pharmacy","4 years","₹1,10,000 / year (indicative)"),new Course("MBA","2 years","₹90,000 / year (indicative)"))),
    new College(12L,"KL University Hyderabad","Hyderabad","Telangana","A technology-oriented university campus with engineering and management programmes.","Hostel and student-life facilities are available; confirm room availability with admissions.","Career development, internships and placement support are provided.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹2,50,000 / year (indicative)"),new Course("B.Tech Electronics & Communication","4 years","₹2,50,000 / year (indicative)"),new Course("MBA","2 years","₹3,00,000 / year (indicative)"))),
    new College(13L,"Woxsen University","Hyderabad","Telangana","A private university offering technology, business, design and liberal arts programmes.","Residential campus accommodation with student facilities is available.","Career services support internships, industry projects and placements.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹4,00,000 / year (indicative)"),new Course("BBA","3 years","₹3,50,000 / year (indicative)"),new Course("B.Des","4 years","₹4,00,000 / year (indicative)"))),
    new College(14L,"ICFAI Foundation for Higher Education","Hyderabad","Telangana","A higher-education campus offering management, engineering, law and science programmes.","Hostel accommodation and campus amenities are available for students.","Career management and placement support are available across schools.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹3,00,000 / year (indicative)"),new Course("BBA","3 years","₹2,50,000 / year (indicative)"),new Course("MBA","2 years","₹4,50,000 / year (indicative)"))),
    new College(15L,"G. Narayanamma Institute of Technology and Science","Hyderabad","Telangana","A women’s engineering institute offering undergraduate and postgraduate technology programmes.","Safe student accommodation and support services are available; verify current hostel options with the institute.","Training and placement activities prepare students for campus recruitment.",List.of(new Course("B.Tech Computer Science Engineering","4 years","₹1,30,000 / year (indicative)"),new Course("B.Tech Information Technology","4 years","₹1,30,000 / year (indicative)"),new Course("B.Tech Artificial Intelligence & Data Science","4 years","₹1,30,000 / year (indicative)")))
  );
  @GetMapping public List<College> search(@RequestParam(defaultValue = "") String query) {
    Set<String> ignoredWords = Set.of("college", "colleges", "in", "of", "the", "for", "and");
    List<String> terms = Arrays.stream(query.toLowerCase().replaceAll("[^a-z0-9 ]", " ").trim().split("\\s+"))
      .filter(term -> !term.isBlank() && !ignoredWords.contains(term)).toList();
    if (terms.isEmpty()) return colleges;
    return colleges.stream().filter(college -> {
      String details = college.name()+" "+college.city()+" "+college.state()+" "+college.description()+" "+college.courses().stream().map(Course::name).reduce("", (a, b) -> a+" "+b);
      String searchable = details.toLowerCase();
      return terms.stream().anyMatch(searchable::contains);
    }).toList();
  }
  @GetMapping("/{id}") public College getOne(@PathVariable Long id) { return colleges.stream().filter(c -> c.id().equals(id)).findFirst().orElseThrow(); }
}
